use_frameworks!

platform :ios, '12.0'

target 'SamUtilsExample' do
  pod 'SamUtils', :podspec => '../SamUtils.podspec'
#  pod 'SamUtils/Bluetooth', :podspec => '../SamUtils.podspec'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
  
end
